apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab-controller-api-deployment
  namespace: lab-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lab-controller-api
  template:
    metadata:
      labels:
        app: lab-controller-api
    spec:
      serviceAccountName: lab-controller-account
      containers:
        - name: lab-controller-api
          image: biolachs2/testing:api
          imagePullPolicy: Always
          ports:
          - containerPort: 5000
          - containerPort: 5001
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: lab-controller-api
  name: lab-controller-api
  namespace: lab-controller
spec:
  selector:
    app: lab-controller-api
  ports:
    - port: 80 # incoming
      name: http
      protocol: TCP
      targetPort: 5000 # port in the pod
      nodePort: 30001
    - port: 5001 # incoming
      name: websockets
      protocol: TCP
      targetPort: 5001 # port in the pod
      nodePort: 30002
  type: NodePort
