kind: Namespace
apiVersion: v1
metadata:
  name: lab-controller
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworldapi-deployment
  namespace: lab-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloworldapi
  template:
    metadata:
      labels:
        app: helloworldapi
    spec:
      containers:
        - name: helloworldapi
          image: USERNAME/REPO:VERSION
          imagePullPolicy: Always
          ports:
          - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: helloworldapi
  name: helloworldapi
  namespace: lab-controller
spec:
  selector:
    app: helloworldapi
  ports:
    - port: 80 # incoming
      protocol: TCP
      targetPort: 5000 # port in the pod
      nodePort: 30001
  type: NodePort
